### GET all contacts
GET http://localhost:8080/contacts

### GET single contact (John Smith)
GET http://localhost:8080/contacts/6a08a91e118eef7b54a3d839

### POST new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane.doe@example.com",
    "favoriteColor": "Yellow",
    "birthday": "1995-12-25"
}

### PUT update contact
PUT http://localhost:8080/contacts/6a08a91e118eef7b54a3d839
Content-Type: application/json

{
    "firstName": "Johnathan",
    "favoriteColor": "Purple"
}

### DELETE contact
DELETE http://localhost:8080/contacts/6a08a91e118eef7b54a3d839